//原始ImageTable数据
export let Rows = [
    {
        Key: 0,
        Type: 'songList',
        imagePath: '/src/assets/song4.jpg',
        SongCount: 10,
        Name: '守时',
        imageSize: [100,300],
    },
    {
        Key: 1,
        Type: 'Song',
        imagePath: '/src/assets/song2.jpg',
        SongCount: 10,
        Name: '给自己的情书',
        imageSize: [200,200],
    },
    {
        Key: 2,
        Type: 'songList',
        imagePath: '/src/assets/song3.jpg',
        SongCount: 10,
        Name: 'Yesterday Once More',
        imageSize: [500,100],
    },
    {
        Key: 3,
        Type: 'songList',
        imagePath: '/src/assets/song3.jpg',
        SongCount: 10,
        Name: 'test112345678765432123456789',
        imageSize: [200,450],
    },
    {
        Key: 4,
        Type: 'Song',
        imagePath: '/src/assets/song5.png',
        SongCount: 10,
        Name: '只因你太美',
        imageSize: [200,250],
    },
    {
        Key: 5,
        Type: 'songList',
        imagePath: '/src/assets/song5.png',
        SongCount: 10,
        Name: 'hahaha',
        imageSize: [500,900],
    },
]